### ISSUE TITLE
gtk3

### ISSUE THREAD

**Issue by yhaenggi** [grassmunk/Platinum9#1]
Hey there

If you ever get time for it, could you port the ClassicPlatinumStreamlined to gtk3 aswell?

**Comment by dotpointer** [comment]
Yes, please port it to GTK 3.20+.

Great job by the way, looks very nice. Your theme works with Debian Stretch 9 + MATE Desktop, only partly though because MATE is transitioning to GTK3 (?).

**Comment by bran** [comment]
Is this theme essentially only fully compatible with XFCE <= 4.12?

I'm trying to use it on XFCE 4.14 and the appearances panel will only show GTK3 compatible themes. I can force GTK2 themes using another GUI theme switcher like lxappearance but the theme doesn't apply to GTK 3 applications. What do I need to do to force GTK 3 applications to use GTK 2 themes?

**Comment by grassmunk** [comment]
I don't really focus on this theme much anymore. But this fork seems to be up to date: https://github.com/timnetworks/Platinum9
