### ISSUE TITLE
I want Xubuntu 20.04 support, like with Chicago95.

### ISSUE THREAD

**Issue by lan-vuhoang** [grassmunk/Platinum9#3]
I want Xubuntu 20.04 support, like with Chicago95. Sure, this theme is outdated, but it definitely still stood a new chance.
Also, add more customization options, like with Chicago95.

**Comment by grassmunk** [comment]
As I mentioned in the other issue, i don't have the time to focus on this and Chicago95, please check out this fork: https://github.com/timnetworks/Platinum9

**Comment by lan-vuhoang** [comment]
It too is outdated.
![Capture](https://user-images.githubusercontent.com/63572082/81554354-d7aa2280-93b0-11ea-825b-93ef6647445b.PNG)

**Comment by lan-vuhoang** [comment]
Seriously, it is outdated. Check it out yourself.

**Comment by lan-vuhoang** [comment]
Seriously. Just check it out yourself. No need to close the issue.

**Comment by yhaenggi** [comment]
Seriously, maybe contribute yourself instead of just complaining.

**Comment by lan-vuhoang** [comment]
Just check it out, OK?

Also, are you even listening?

**Comment by lan-vuhoang** [comment]
28 days later and it's still outdated.

Also, since Github's UI has changed recently, here's an updated photo:

![image](https://user-images.githubusercontent.com/63572082/85920998-d1113500-b8a2-11ea-964b-382d326e6108.png)

Last commit: f0b7214 on 1 Jul, 2019
